# -*- coding: utf-8 -*-
"""Guess who won the super bowl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JAb2LoAN9_aqbY6aBOYgOBUxnlLSQBqO

"Guess the super bowl winner"
1. Display a welcome message
2. Generate a random year to guess who won the superbowl
3. Give the user 3 tries to guess the superbowl winner
4. Give the user the option to play again

#Guess the SB winner <code>
"""

import pandas as pd
sblist = pd.read_csv('sblist.csv')
sblist['Winner'] = sblist['Winner'].str.strip()

def superbowlguesser():
  #Display a welcome message
  welcome_message = "Welcome! We'll give you a Super Bowl, you have 3 tries to guess who won."
  print(welcome_message)
  print("-" * 30)

#Generate SB to guess
  winning_sb = sblist.sample()
  guess = winning_sb['SB'].to_string(index=False)
  team2guess = winning_sb['Winner'].to_string(index=False).strip()
  print(f"Who won Superbowl {guess}?\n")
  
# 3 guesses start here
  tries_remaining = 3
  while tries_remaining > 0:
     print("-" * 30)
     guess_team = input("What is your guess?\n")
     guess_team.strip()
     if guess_team == team2guess:
      print(f"Congrats! {guess_team} is correct!\n")
      break
     else:
      tries_remaining -= 1
      print(f'\nInncorrect. You have {tries_remaining} tries left.')

     if tries_remaining == 0:
      print(f'\nGame over. The winning team was {team2guess}.')

#Give option to play again
  play_again = input("\nWould you like to play again? (y/n)\n")
  if play_again == "y":
    return superbowlguesser()
  elif play_again == 'n':
    print("Thanks. Until next time...")

"""#Play# New Section"""

superbowlguesser()